//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 20.04.2008 12:25:59
namespace ReferenceFrameworkModel
{
    
    /// <summary>
    /// There are no comments for ReferenceFrameworkEntities in the schema.
    /// </summary>
    public partial class ReferenceFrameworkEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ReferenceFrameworkEntities object using the connection string found in the 'ReferenceFrameworkEntities' section of the application configuration file.
        /// </summary>
        public ReferenceFrameworkEntities() : 
                base("name=ReferenceFrameworkEntities", "ReferenceFrameworkEntities")
        {
        }
        /// <summary>
        /// Initialize a new ReferenceFrameworkEntities object.
        /// </summary>
        public ReferenceFrameworkEntities(string connectionString) : 
                base(connectionString, "ReferenceFrameworkEntities")
        {
        }
        /// <summary>
        /// Initialize a new ReferenceFrameworkEntities object.
        /// </summary>
        public ReferenceFrameworkEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ReferenceFrameworkEntities")
        {
        }
        /// <summary>
        /// There are no comments for ActionType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<ActionType> ActionType
        {
            get
            {
                if ((this._ActionType == null))
                {
                    this._ActionType = base.CreateQuery<ActionType>("[ActionType]");
                }
                return this._ActionType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ActionType> _ActionType;
        /// <summary>
        /// There are no comments for Care_Component in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Care_Component> Care_Component
        {
            get
            {
                if ((this._Care_Component == null))
                {
                    this._Care_Component = base.CreateQuery<Care_Component>("[Care_Component]");
                }
                return this._Care_Component;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Care_Component> _Care_Component;
        /// <summary>
        /// There are no comments for Nursing_Diagnosis in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Nursing_Diagnosis> Nursing_Diagnosis
        {
            get
            {
                if ((this._Nursing_Diagnosis == null))
                {
                    this._Nursing_Diagnosis = base.CreateQuery<Nursing_Diagnosis>("[Nursing_Diagnosis]");
                }
                return this._Nursing_Diagnosis;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Nursing_Diagnosis> _Nursing_Diagnosis;
        /// <summary>
        /// There are no comments for Nursing_Intervention in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Nursing_Intervention> Nursing_Intervention
        {
            get
            {
                if ((this._Nursing_Intervention == null))
                {
                    this._Nursing_Intervention = base.CreateQuery<Nursing_Intervention>("[Nursing_Intervention]");
                }
                return this._Nursing_Intervention;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Nursing_Intervention> _Nursing_Intervention;
        /// <summary>
        /// There are no comments for OutcomeType in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<OutcomeType> OutcomeType
        {
            get
            {
                if ((this._OutcomeType == null))
                {
                    this._OutcomeType = base.CreateQuery<OutcomeType>("[OutcomeType]");
                }
                return this._OutcomeType;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OutcomeType> _OutcomeType;
        /// <summary>
        /// There are no comments for ActionType in the schema.
        /// </summary>
        public void AddToActionType(ActionType actionType)
        {
            base.AddObject("ActionType", actionType);
        }
        /// <summary>
        /// There are no comments for Care_Component in the schema.
        /// </summary>
        public void AddToCare_Component(Care_Component care_Component)
        {
            base.AddObject("Care_Component", care_Component);
        }
        /// <summary>
        /// There are no comments for Nursing_Diagnosis in the schema.
        /// </summary>
        public void AddToNursing_Diagnosis(Nursing_Diagnosis nursing_Diagnosis)
        {
            base.AddObject("Nursing_Diagnosis", nursing_Diagnosis);
        }
        /// <summary>
        /// There are no comments for Nursing_Intervention in the schema.
        /// </summary>
        public void AddToNursing_Intervention(Nursing_Intervention nursing_Intervention)
        {
            base.AddObject("Nursing_Intervention", nursing_Intervention);
        }
        /// <summary>
        /// There are no comments for OutcomeType in the schema.
        /// </summary>
        public void AddToOutcomeType(OutcomeType outcomeType)
        {
            base.AddObject("OutcomeType", outcomeType);
        }
    }
    /// <summary>
    /// There are no comments for ReferenceFrameworkModel.ActionType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagGuid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ReferenceFrameworkModel", Name="ActionType")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class ActionType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ActionType object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="concept">Initial value of Concept.</param>
        /// <param name="tagGuid">Initial value of TagGuid.</param>
        public static ActionType CreateActionType(string version, short code, string concept, global::System.Guid tagGuid)
        {
            ActionType actionType = new ActionType();
            actionType.Version = version;
            actionType.Code = code;
            actionType.Concept = concept;
            actionType.TagGuid = tagGuid;
            return actionType;
        }
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 10);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private short _Code;
        partial void OnCodeChanging(short value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Concept in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Concept
        {
            get
            {
                return this._Concept;
            }
            set
            {
                this.OnConceptChanging(value);
                this.ReportPropertyChanging("Concept");
                this._Concept = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 100);
                this.ReportPropertyChanged("Concept");
                this.OnConceptChanged();
            }
        }
        private string _Concept;
        partial void OnConceptChanging(string value);
        partial void OnConceptChanged();
        /// <summary>
        /// There are no comments for Property Definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition
        {
            get
            {
                return this._Definition;
            }
            set
            {
                this.OnDefinitionChanging(value);
                this.ReportPropertyChanging("Definition");
                this._Definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Definition");
                this.OnDefinitionChanged();
            }
        }
        private string _Definition;
        partial void OnDefinitionChanging(string value);
        partial void OnDefinitionChanged();
        /// <summary>
        /// There are no comments for Property TagGuid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TagGuid
        {
            get
            {
                return this._TagGuid;
            }
            set
            {
                this.OnTagGuidChanging(value);
                this.ReportPropertyChanging("TagGuid");
                this._TagGuid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagGuid");
                this.OnTagGuidChanged();
            }
        }
        private global::System.Guid _TagGuid;
        partial void OnTagGuidChanging(global::System.Guid value);
        partial void OnTagGuidChanged();
    }
    /// <summary>
    /// There are no comments for ReferenceFrameworkModel.Care_Component in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagGuid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ReferenceFrameworkModel", Name="Care_Component")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Care_Component : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Care_Component object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="concept">Initial value of Concept.</param>
        /// <param name="definition">Initial value of Definition.</param>
        /// <param name="tagGuid">Initial value of TagGuid.</param>
        public static Care_Component CreateCare_Component(string version, string code, string concept, string definition, global::System.Guid tagGuid)
        {
            Care_Component care_Component = new Care_Component();
            care_Component.Version = version;
            care_Component.Code = code;
            care_Component.Concept = concept;
            care_Component.Definition = definition;
            care_Component.TagGuid = tagGuid;
            return care_Component;
        }
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 10);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 1);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Concept in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Concept
        {
            get
            {
                return this._Concept;
            }
            set
            {
                this.OnConceptChanging(value);
                this.ReportPropertyChanging("Concept");
                this._Concept = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 100);
                this.ReportPropertyChanged("Concept");
                this.OnConceptChanged();
            }
        }
        private string _Concept;
        partial void OnConceptChanging(string value);
        partial void OnConceptChanged();
        /// <summary>
        /// There are no comments for Property Definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition
        {
            get
            {
                return this._Definition;
            }
            set
            {
                this.OnDefinitionChanging(value);
                this.ReportPropertyChanging("Definition");
                this._Definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 255);
                this.ReportPropertyChanged("Definition");
                this.OnDefinitionChanged();
            }
        }
        private string _Definition;
        partial void OnDefinitionChanging(string value);
        partial void OnDefinitionChanged();
        /// <summary>
        /// There are no comments for Property TagGuid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TagGuid
        {
            get
            {
                return this._TagGuid;
            }
            set
            {
                this.OnTagGuidChanging(value);
                this.ReportPropertyChanging("TagGuid");
                this._TagGuid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagGuid");
                this.OnTagGuidChanged();
            }
        }
        private global::System.Guid _TagGuid;
        partial void OnTagGuidChanging(global::System.Guid value);
        partial void OnTagGuidChanged();
    }
    /// <summary>
    /// There are no comments for ReferenceFrameworkModel.Nursing_Diagnosis in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagGuid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ReferenceFrameworkModel", Name="Nursing_Diagnosis")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Nursing_Diagnosis : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Nursing_Diagnosis object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="componentCode">Initial value of ComponentCode.</param>
        /// <param name="majorCode">Initial value of MajorCode.</param>
        /// <param name="concept">Initial value of Concept.</param>
        /// <param name="definition">Initial value of Definition.</param>
        /// <param name="tagGuid">Initial value of TagGuid.</param>
        public static Nursing_Diagnosis CreateNursing_Diagnosis(string version, string componentCode, short majorCode, string concept, string definition, global::System.Guid tagGuid)
        {
            Nursing_Diagnosis nursing_Diagnosis = new Nursing_Diagnosis();
            nursing_Diagnosis.Version = version;
            nursing_Diagnosis.ComponentCode = componentCode;
            nursing_Diagnosis.MajorCode = majorCode;
            nursing_Diagnosis.Concept = concept;
            nursing_Diagnosis.Definition = definition;
            nursing_Diagnosis.TagGuid = tagGuid;
            return nursing_Diagnosis;
        }
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 10);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property ComponentCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentCode
        {
            get
            {
                return this._ComponentCode;
            }
            set
            {
                this.OnComponentCodeChanging(value);
                this.ReportPropertyChanging("ComponentCode");
                this._ComponentCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 1);
                this.ReportPropertyChanged("ComponentCode");
                this.OnComponentCodeChanged();
            }
        }
        private string _ComponentCode;
        partial void OnComponentCodeChanging(string value);
        partial void OnComponentCodeChanged();
        /// <summary>
        /// There are no comments for Property MajorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short MajorCode
        {
            get
            {
                return this._MajorCode;
            }
            set
            {
                this.OnMajorCodeChanging(value);
                this.ReportPropertyChanging("MajorCode");
                this._MajorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MajorCode");
                this.OnMajorCodeChanged();
            }
        }
        private short _MajorCode;
        partial void OnMajorCodeChanging(short value);
        partial void OnMajorCodeChanged();
        /// <summary>
        /// There are no comments for Property MinorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> MinorCode
        {
            get
            {
                return this._MinorCode;
            }
            set
            {
                this.OnMinorCodeChanging(value);
                this.ReportPropertyChanging("MinorCode");
                this._MinorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinorCode");
                this.OnMinorCodeChanged();
            }
        }
        private global::System.Nullable<short> _MinorCode;
        partial void OnMinorCodeChanging(global::System.Nullable<short> value);
        partial void OnMinorCodeChanged();
        /// <summary>
        /// There are no comments for Property Concept in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Concept
        {
            get
            {
                return this._Concept;
            }
            set
            {
                this.OnConceptChanging(value);
                this.ReportPropertyChanging("Concept");
                this._Concept = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 100);
                this.ReportPropertyChanged("Concept");
                this.OnConceptChanged();
            }
        }
        private string _Concept;
        partial void OnConceptChanging(string value);
        partial void OnConceptChanged();
        /// <summary>
        /// There are no comments for Property Definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition
        {
            get
            {
                return this._Definition;
            }
            set
            {
                this.OnDefinitionChanging(value);
                this.ReportPropertyChanging("Definition");
                this._Definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 255);
                this.ReportPropertyChanged("Definition");
                this.OnDefinitionChanged();
            }
        }
        private string _Definition;
        partial void OnDefinitionChanging(string value);
        partial void OnDefinitionChanged();
        /// <summary>
        /// There are no comments for Property TagGuid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TagGuid
        {
            get
            {
                return this._TagGuid;
            }
            set
            {
                this.OnTagGuidChanging(value);
                this.ReportPropertyChanging("TagGuid");
                this._TagGuid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagGuid");
                this.OnTagGuidChanged();
            }
        }
        private global::System.Guid _TagGuid;
        partial void OnTagGuidChanging(global::System.Guid value);
        partial void OnTagGuidChanged();
    }
    /// <summary>
    /// There are no comments for ReferenceFrameworkModel.Nursing_Intervention in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagGuid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ReferenceFrameworkModel", Name="Nursing_Intervention")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Nursing_Intervention : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Nursing_Intervention object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="componentCode">Initial value of ComponentCode.</param>
        /// <param name="majorCode">Initial value of MajorCode.</param>
        /// <param name="concept">Initial value of Concept.</param>
        /// <param name="definition">Initial value of Definition.</param>
        /// <param name="tagGuid">Initial value of TagGuid.</param>
        public static Nursing_Intervention CreateNursing_Intervention(string version, string componentCode, short majorCode, string concept, string definition, global::System.Guid tagGuid)
        {
            Nursing_Intervention nursing_Intervention = new Nursing_Intervention();
            nursing_Intervention.Version = version;
            nursing_Intervention.ComponentCode = componentCode;
            nursing_Intervention.MajorCode = majorCode;
            nursing_Intervention.Concept = concept;
            nursing_Intervention.Definition = definition;
            nursing_Intervention.TagGuid = tagGuid;
            return nursing_Intervention;
        }
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 10);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property ComponentCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentCode
        {
            get
            {
                return this._ComponentCode;
            }
            set
            {
                this.OnComponentCodeChanging(value);
                this.ReportPropertyChanging("ComponentCode");
                this._ComponentCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 1);
                this.ReportPropertyChanged("ComponentCode");
                this.OnComponentCodeChanged();
            }
        }
        private string _ComponentCode;
        partial void OnComponentCodeChanging(string value);
        partial void OnComponentCodeChanged();
        /// <summary>
        /// There are no comments for Property MajorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short MajorCode
        {
            get
            {
                return this._MajorCode;
            }
            set
            {
                this.OnMajorCodeChanging(value);
                this.ReportPropertyChanging("MajorCode");
                this._MajorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MajorCode");
                this.OnMajorCodeChanged();
            }
        }
        private short _MajorCode;
        partial void OnMajorCodeChanging(short value);
        partial void OnMajorCodeChanged();
        /// <summary>
        /// There are no comments for Property MinorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> MinorCode
        {
            get
            {
                return this._MinorCode;
            }
            set
            {
                this.OnMinorCodeChanging(value);
                this.ReportPropertyChanging("MinorCode");
                this._MinorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinorCode");
                this.OnMinorCodeChanged();
            }
        }
        private global::System.Nullable<short> _MinorCode;
        partial void OnMinorCodeChanging(global::System.Nullable<short> value);
        partial void OnMinorCodeChanged();
        /// <summary>
        /// There are no comments for Property Concept in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Concept
        {
            get
            {
                return this._Concept;
            }
            set
            {
                this.OnConceptChanging(value);
                this.ReportPropertyChanging("Concept");
                this._Concept = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 100);
                this.ReportPropertyChanged("Concept");
                this.OnConceptChanged();
            }
        }
        private string _Concept;
        partial void OnConceptChanging(string value);
        partial void OnConceptChanged();
        /// <summary>
        /// There are no comments for Property Definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition
        {
            get
            {
                return this._Definition;
            }
            set
            {
                this.OnDefinitionChanging(value);
                this.ReportPropertyChanging("Definition");
                this._Definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 255);
                this.ReportPropertyChanged("Definition");
                this.OnDefinitionChanged();
            }
        }
        private string _Definition;
        partial void OnDefinitionChanging(string value);
        partial void OnDefinitionChanged();
        /// <summary>
        /// There are no comments for Property TagGuid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TagGuid
        {
            get
            {
                return this._TagGuid;
            }
            set
            {
                this.OnTagGuidChanging(value);
                this.ReportPropertyChanging("TagGuid");
                this._TagGuid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagGuid");
                this.OnTagGuidChanged();
            }
        }
        private global::System.Guid _TagGuid;
        partial void OnTagGuidChanging(global::System.Guid value);
        partial void OnTagGuidChanged();
    }
    /// <summary>
    /// There are no comments for ReferenceFrameworkModel.OutcomeType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagGuid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ReferenceFrameworkModel", Name="OutcomeType")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class OutcomeType : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OutcomeType object.
        /// </summary>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="concept">Initial value of Concept.</param>
        /// <param name="tagGuid">Initial value of TagGuid.</param>
        public static OutcomeType CreateOutcomeType(string version, short code, string concept, global::System.Guid tagGuid)
        {
            OutcomeType outcomeType = new OutcomeType();
            outcomeType.Version = version;
            outcomeType.Code = code;
            outcomeType.Concept = concept;
            outcomeType.TagGuid = tagGuid;
            return outcomeType;
        }
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 10);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private short _Code;
        partial void OnCodeChanging(short value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Concept in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Concept
        {
            get
            {
                return this._Concept;
            }
            set
            {
                this.OnConceptChanging(value);
                this.ReportPropertyChanging("Concept");
                this._Concept = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 100);
                this.ReportPropertyChanged("Concept");
                this.OnConceptChanged();
            }
        }
        private string _Concept;
        partial void OnConceptChanging(string value);
        partial void OnConceptChanged();
        /// <summary>
        /// There are no comments for Property Definition in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Definition
        {
            get
            {
                return this._Definition;
            }
            set
            {
                this.OnDefinitionChanging(value);
                this.ReportPropertyChanging("Definition");
                this._Definition = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Definition");
                this.OnDefinitionChanged();
            }
        }
        private string _Definition;
        partial void OnDefinitionChanging(string value);
        partial void OnDefinitionChanged();
        /// <summary>
        /// There are no comments for Property TagGuid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TagGuid
        {
            get
            {
                return this._TagGuid;
            }
            set
            {
                this.OnTagGuidChanging(value);
                this.ReportPropertyChanging("TagGuid");
                this._TagGuid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagGuid");
                this.OnTagGuidChanged();
            }
        }
        private global::System.Guid _TagGuid;
        partial void OnTagGuidChanging(global::System.Guid value);
        partial void OnTagGuidChanged();
    }
}
