//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 20.04.2008 12:25:59
namespace eNursePHR.BusinessLayer
{
    
    /// <summary>
    /// There are no comments for MeasurementsEntities in the schema.
    /// </summary>
    public partial class MeasurementsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MeasurementsEntities object using the connection string found in the 'MeasurementsEntities' section of the application configuration file.
        /// </summary>
        public MeasurementsEntities() : 
                base("name=MeasurementsEntities", "MeasurementsEntities")
        {
        }
        /// <summary>
        /// Initialize a new MeasurementsEntities object.
        /// </summary>
        public MeasurementsEntities(string connectionString) : 
                base(connectionString, "MeasurementsEntities")
        {
        }
        /// <summary>
        /// Initialize a new MeasurementsEntities object.
        /// </summary>
        public MeasurementsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MeasurementsEntities")
        {
        }
        /// <summary>
        /// There are no comments for BloodPressure in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<BloodPressure> BloodPressure
        {
            get
            {
                if ((this._BloodPressure == null))
                {
                    this._BloodPressure = base.CreateQuery<BloodPressure>("[BloodPressure]");
                }
                return this._BloodPressure;
            }
        }
        private global::System.Data.Objects.ObjectQuery<BloodPressure> _BloodPressure;
        /// <summary>
        /// There are no comments for Respiration in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Respiration> Respiration
        {
            get
            {
                if ((this._Respiration == null))
                {
                    this._Respiration = base.CreateQuery<Respiration>("[Respiration]");
                }
                return this._Respiration;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Respiration> _Respiration;
        /// <summary>
        /// There are no comments for Temperature in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Temperature> Temperature
        {
            get
            {
                if ((this._Temperature == null))
                {
                    this._Temperature = base.CreateQuery<Temperature>("[Temperature]");
                }
                return this._Temperature;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Temperature> _Temperature;
        /// <summary>
        /// There are no comments for BloodPressure in the schema.
        /// </summary>
        public void AddToBloodPressure(BloodPressure bloodPressure)
        {
            base.AddObject("BloodPressure", bloodPressure);
        }
        /// <summary>
        /// There are no comments for Respiration in the schema.
        /// </summary>
        public void AddToRespiration(Respiration respiration)
        {
            base.AddObject("Respiration", respiration);
        }
        /// <summary>
        /// There are no comments for Temperature in the schema.
        /// </summary>
        public void AddToTemperature(Temperature temperature)
        {
            base.AddObject("Temperature", temperature);
        }
    }
    /// <summary>
    /// There are no comments for eNursePHR.BusinessLayer.BloodPressure in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Time
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNursePHR.BusinessLayer", Name="BloodPressure")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class BloodPressure : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new BloodPressure object.
        /// </summary>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="carePlanId">Initial value of CarePlanId.</param>
        public static BloodPressure CreateBloodPressure(global::System.DateTime time, global::System.Guid carePlanId)
        {
            BloodPressure bloodPressure = new BloodPressure();
            bloodPressure.Time = time;
            bloodPressure.CarePlanId = carePlanId;
            return bloodPressure;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SystolicBP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> SystolicBP
        {
            get
            {
                return this._SystolicBP;
            }
            set
            {
                this.OnSystolicBPChanging(value);
                this.ReportPropertyChanging("SystolicBP");
                this._SystolicBP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SystolicBP");
                this.OnSystolicBPChanged();
            }
        }
        private global::System.Nullable<int> _SystolicBP;
        partial void OnSystolicBPChanging(global::System.Nullable<int> value);
        partial void OnSystolicBPChanged();
        /// <summary>
        /// There are no comments for Property DiastolicBP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> DiastolicBP
        {
            get
            {
                return this._DiastolicBP;
            }
            set
            {
                this.OnDiastolicBPChanging(value);
                this.ReportPropertyChanging("DiastolicBP");
                this._DiastolicBP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DiastolicBP");
                this.OnDiastolicBPChanged();
            }
        }
        private global::System.Nullable<int> _DiastolicBP;
        partial void OnDiastolicBPChanging(global::System.Nullable<int> value);
        partial void OnDiastolicBPChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property CarePlanId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid CarePlanId
        {
            get
            {
                return this._CarePlanId;
            }
            set
            {
                this.OnCarePlanIdChanging(value);
                this.ReportPropertyChanging("CarePlanId");
                this._CarePlanId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CarePlanId");
                this.OnCarePlanIdChanged();
            }
        }
        private global::System.Guid _CarePlanId;
        partial void OnCarePlanIdChanging(global::System.Guid value);
        partial void OnCarePlanIdChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Pulse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Pulse
        {
            get
            {
                return this._Pulse;
            }
            set
            {
                this.OnPulseChanging(value);
                this.ReportPropertyChanging("Pulse");
                this._Pulse = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Pulse");
                this.OnPulseChanged();
            }
        }
        private global::System.Nullable<int> _Pulse;
        partial void OnPulseChanging(global::System.Nullable<int> value);
        partial void OnPulseChanged();
    }
    /// <summary>
    /// There are no comments for eNursePHR.BusinessLayer.Respiration in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Time
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNursePHR.BusinessLayer", Name="Respiration")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Respiration : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Respiration object.
        /// </summary>
        /// <param name="time">Initial value of Time.</param>
        public static Respiration CreateRespiration(global::System.DateTime time)
        {
            Respiration respiration = new Respiration();
            respiration.Time = time;
            return respiration;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SaO2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<double> SaO2
        {
            get
            {
                return this._SaO2;
            }
            set
            {
                this.OnSaO2Changing(value);
                this.ReportPropertyChanging("SaO2");
                this._SaO2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SaO2");
                this.OnSaO2Changed();
            }
        }
        private global::System.Nullable<double> _SaO2;
        partial void OnSaO2Changing(global::System.Nullable<double> value);
        partial void OnSaO2Changed();
        /// <summary>
        /// There are no comments for Property Frequency in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> Frequency
        {
            get
            {
                return this._Frequency;
            }
            set
            {
                this.OnFrequencyChanging(value);
                this.ReportPropertyChanging("Frequency");
                this._Frequency = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Frequency");
                this.OnFrequencyChanged();
            }
        }
        private global::System.Nullable<short> _Frequency;
        partial void OnFrequencyChanging(global::System.Nullable<short> value);
        partial void OnFrequencyChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
    }
    /// <summary>
    /// There are no comments for eNursePHR.BusinessLayer.Temperature in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Time
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNursePHR.BusinessLayer", Name="Temperature")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Temperature : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Temperature object.
        /// </summary>
        /// <param name="temp">Initial value of Temp.</param>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="locationCode">Initial value of LocationCode.</param>
        public static Temperature CreateTemperature(double temp, global::System.DateTime time, short locationCode)
        {
            Temperature temperature = new Temperature();
            temperature.Temp = temp;
            temperature.Time = time;
            temperature.LocationCode = locationCode;
            return temperature;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _Id;
        partial void OnIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Temp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public double Temp
        {
            get
            {
                return this._Temp;
            }
            set
            {
                this.OnTempChanging(value);
                this.ReportPropertyChanging("Temp");
                this._Temp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Temp");
                this.OnTempChanged();
            }
        }
        private double _Temp;
        partial void OnTempChanging(double value);
        partial void OnTempChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property LocationCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short LocationCode
        {
            get
            {
                return this._LocationCode;
            }
            set
            {
                this.OnLocationCodeChanging(value);
                this.ReportPropertyChanging("LocationCode");
                this._LocationCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LocationCode");
                this.OnLocationCodeChanged();
            }
        }
        private short _LocationCode;
        partial void OnLocationCodeChanging(short value);
        partial void OnLocationCodeChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
    }
}
