//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_History_ActionT", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.History), "ActionT", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.ActionT))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_Tag_ActionT", "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eNurseCP.BusinessLayer.Tag), "ActionT", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.ActionT))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_History_Annotation", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.History), "Annotation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.CPAnnotation))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_Item_Annotation", "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eNurseCP.BusinessLayer.Item), "Annotation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.CPAnnotation))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_CarePlan_Item", "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eNurseCP.BusinessLayer.CarePlan), "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.Item))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_History_CarePlan", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.History), "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.CarePlan))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_History_Item", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.History), "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.Item))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_Outcome_History", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.History), "Outcome", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.Outcome))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_Tag_History", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eNurseCP.BusinessLayer.History), "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(eNurseCP.BusinessLayer.Tag))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_Tag_Item", "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eNurseCP.BusinessLayer.Item), "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.Tag))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("eNurseCP.BusinessLayer", "FK_Outcome_Tag", "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(eNurseCP.BusinessLayer.Tag), "Outcome", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(eNurseCP.BusinessLayer.Outcome))]

// Original file name:
// Generation date: 13.04.2008 14:10:09
namespace eNurseCP.BusinessLayer
{
    
    /// <summary>
    /// There are no comments for CarePlanEntities in the schema.
    /// </summary>
    public partial class CarePlanEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CarePlanEntities object using the connection string found in the 'CarePlanEntities' section of the application configuration file.
        /// </summary>
        public CarePlanEntities() : 
                base("name=CarePlanEntities", "CarePlanEntities")
        {
        }
        /// <summary>
        /// Initialize a new CarePlanEntities object.
        /// </summary>
        public CarePlanEntities(string connectionString) : 
                base(connectionString, "CarePlanEntities")
        {
        }
        /// <summary>
        /// Initialize a new CarePlanEntities object.
        /// </summary>
        public CarePlanEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CarePlanEntities")
        {
        }
        /// <summary>
        /// There are no comments for ActionT in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<ActionT> ActionT
        {
            get
            {
                if ((this._ActionT == null))
                {
                    this._ActionT = base.CreateQuery<ActionT>("[ActionT]");
                }
                return this._ActionT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ActionT> _ActionT;
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<CPAnnotation> Annotation
        {
            get
            {
                if ((this._Annotation == null))
                {
                    this._Annotation = base.CreateQuery<CPAnnotation>("[Annotation]");
                }
                return this._Annotation;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CPAnnotation> _Annotation;
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<CarePlan> CarePlan
        {
            get
            {
                if ((this._CarePlan == null))
                {
                    this._CarePlan = base.CreateQuery<CarePlan>("[CarePlan]");
                }
                return this._CarePlan;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarePlan> _CarePlan;
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<History> History
        {
            get
            {
                if ((this._History == null))
                {
                    this._History = base.CreateQuery<History>("[History]");
                }
                return this._History;
            }
        }
        private global::System.Data.Objects.ObjectQuery<History> _History;
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Item> Item
        {
            get
            {
                if ((this._Item == null))
                {
                    this._Item = base.CreateQuery<Item>("[Item]");
                }
                return this._Item;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Item> _Item;
        /// <summary>
        /// There are no comments for Outcome in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Outcome> Outcome
        {
            get
            {
                if ((this._Outcome == null))
                {
                    this._Outcome = base.CreateQuery<Outcome>("[Outcome]");
                }
                return this._Outcome;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Outcome> _Outcome;
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Tag> Tag
        {
            get
            {
                if ((this._Tag == null))
                {
                    this._Tag = base.CreateQuery<Tag>("[Tag]");
                }
                return this._Tag;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tag> _Tag;
        /// <summary>
        /// There are no comments for ActionT in the schema.
        /// </summary>
        public void AddToActionT(ActionT actionT)
        {
            base.AddObject("ActionT", actionT);
        }
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        public void AddToAnnotation(CPAnnotation cPAnnotation)
        {
            base.AddObject("Annotation", cPAnnotation);
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        public void AddToCarePlan(CarePlan carePlan)
        {
            base.AddObject("CarePlan", carePlan);
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        public void AddToHistory(History history)
        {
            base.AddObject("History", history);
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
        /// <summary>
        /// There are no comments for Outcome in the schema.
        /// </summary>
        public void AddToOutcome(Outcome outcome)
        {
            base.AddObject("Outcome", outcome);
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        public void AddToTag(Tag tag)
        {
            base.AddObject("Tag", tag);
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.ActionT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// TagId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="ActionT")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class ActionT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ActionT object.
        /// </summary>
        /// <param name="code">Initial value of Code.</param>
        /// <param name="singleConcept">Initial value of SingleConcept.</param>
        /// <param name="taxonomyTagId">Initial value of TaxonomyTagId.</param>
        /// <param name="tagId">Initial value of TagId.</param>
        public static ActionT CreateActionT(short code, string singleConcept, global::System.Guid taxonomyTagId, global::System.Guid tagId)
        {
            ActionT actionT = new ActionT();
            actionT.Code = code;
            actionT.SingleConcept = singleConcept;
            actionT.TaxonomyTagId = taxonomyTagId;
            actionT.TagId = tagId;
            return actionT;
        }
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this.ReportPropertyChanging("Code");
                this._Code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Code");
                this.OnCodeChanged();
            }
        }
        private short _Code;
        partial void OnCodeChanging(short value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property SingleConcept in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SingleConcept
        {
            get
            {
                return this._SingleConcept;
            }
            set
            {
                this.OnSingleConceptChanging(value);
                this.ReportPropertyChanging("SingleConcept");
                this._SingleConcept = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 30);
                this.ReportPropertyChanged("SingleConcept");
                this.OnSingleConceptChanged();
            }
        }
        private string _SingleConcept;
        partial void OnSingleConceptChanging(string value);
        partial void OnSingleConceptChanged();
        /// <summary>
        /// There are no comments for Property TaxonomyTagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonomyTagId
        {
            get
            {
                return this._TaxonomyTagId;
            }
            set
            {
                this.OnTaxonomyTagIdChanging(value);
                this.ReportPropertyChanging("TaxonomyTagId");
                this._TaxonomyTagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonomyTagId");
                this.OnTaxonomyTagIdChanged();
            }
        }
        private global::System.Guid _TaxonomyTagId;
        partial void OnTaxonomyTagIdChanging(global::System.Guid value);
        partial void OnTaxonomyTagIdChanged();
        /// <summary>
        /// There are no comments for Property TagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TagId
        {
            get
            {
                return this._TagId;
            }
            set
            {
                this.OnTagIdChanging(value);
                this.ReportPropertyChanging("TagId");
                this._TagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TagId");
                this.OnTagIdChanged();
            }
        }
        private global::System.Guid _TagId;
        partial void OnTagIdChanging(global::System.Guid value);
        partial void OnTagIdChanged();
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_ActionT", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_ActionT", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_ActionT", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_ActionT", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_ActionT", "History", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Tag_ActionT", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Tag Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "Tag").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "Tag").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Tag> TagReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "Tag", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.CPAnnotation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="CPAnnotation")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class CPAnnotation : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CPAnnotation object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static CPAnnotation CreateCPAnnotation(global::System.Guid ID)
        {
            CPAnnotation cPAnnotation = new CPAnnotation();
            cPAnnotation.Id = ID;
            return cPAnnotation;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Data);
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 1073741823);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private byte[] _Data;
        partial void OnDataChanging(byte[] value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_Annotation", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Annotation", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Annotation", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Annotation", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Annotation", "History", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Item_Annotation", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Item Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Item_Annotation", "Item").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Item_Annotation", "Item").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Item> ItemReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Item_Annotation", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Item_Annotation", "Item", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.CarePlan in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="CarePlan")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class CarePlan : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarePlan object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static CarePlan CreateCarePlan(global::System.Guid ID)
        {
            CarePlan carePlan = new CarePlan();
            carePlan.Id = ID;
            return carePlan;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property TemplateCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> TemplateCategoryID
        {
            get
            {
                return this._TemplateCategoryID;
            }
            set
            {
                this.OnTemplateCategoryIDChanging(value);
                this.ReportPropertyChanging("TemplateCategoryID");
                this._TemplateCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TemplateCategoryID");
                this.OnTemplateCategoryIDChanged();
            }
        }
        private global::System.Nullable<short> _TemplateCategoryID;
        partial void OnTemplateCategoryIDChanging(global::System.Nullable<short> value);
        partial void OnTemplateCategoryIDChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this.ReportPropertyChanging("PatientId");
                this._PatientId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PatientId");
                this.OnPatientIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _PatientId;
        partial void OnPatientIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Description
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Description);
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 1073741823);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private byte[] _Description;
        partial void OnDescriptionChanging(byte[] value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_CarePlan_Item", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Item> Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Item>("eNurseCP.BusinessLayer.FK_CarePlan_Item", "Item");
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_CarePlan", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_CarePlan", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_CarePlan", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_CarePlan", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_CarePlan", "History", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="History")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class History : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new History object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        public static History CreateHistory(global::System.Guid ID, global::System.DateTime createdDate, string createdBy)
        {
            History history = new History();
            history.Id = ID;
            history.CreatedDate = createdDate;
            history.CreatedBy = createdBy;
            return history;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 150);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property UpdatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
            set
            {
                this.OnUpdatedDateChanging(value);
                this.ReportPropertyChanging("UpdatedDate");
                this._UpdatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("UpdatedDate");
                this.OnUpdatedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();
        /// <summary>
        /// There are no comments for Property UpdatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy
        {
            get
            {
                return this._UpdatedBy;
            }
            set
            {
                this.OnUpdatedByChanging(value);
                this.ReportPropertyChanging("UpdatedBy");
                this._UpdatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 150);
                this.ReportPropertyChanged("UpdatedBy");
                this.OnUpdatedByChanged();
            }
        }
        private string _UpdatedBy;
        partial void OnUpdatedByChanging(string value);
        partial void OnUpdatedByChanged();
        /// <summary>
        /// There are no comments for ActionT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_ActionT", "ActionT")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<ActionT> ActionT
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ActionT>("eNurseCP.BusinessLayer.FK_History_ActionT", "ActionT");
            }
        }
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_Annotation", "Annotation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<CPAnnotation> Annotation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CPAnnotation>("eNurseCP.BusinessLayer.FK_History_Annotation", "Annotation");
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_CarePlan", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarePlan> CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarePlan>("eNurseCP.BusinessLayer.FK_History_CarePlan", "CarePlan");
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_Item", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Item> Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Item>("eNurseCP.BusinessLayer.FK_History_Item", "Item");
            }
        }
        /// <summary>
        /// There are no comments for Outcome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Outcome_History", "Outcome")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Outcome> Outcome
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Outcome>("eNurseCP.BusinessLayer.FK_Outcome_History", "Outcome");
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Tag_History", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Tag Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_History", "Tag").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_History", "Tag").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Tag> TagReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_History", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Tag_History", "Tag", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="Item")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Item : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        public static Item CreateItem(global::System.Guid ID, string title)
        {
            Item item = new Item();
            item.Id = ID;
            item.Title = title;
            return item;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 255);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Description
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Description);
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 1073741823);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private byte[] _Description;
        partial void OnDescriptionChanging(byte[] value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ContainsDiagnosis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ContainsDiagnosis
        {
            get
            {
                return this._ContainsDiagnosis;
            }
            set
            {
                this.OnContainsDiagnosisChanging(value);
                this.ReportPropertyChanging("ContainsDiagnosis");
                this._ContainsDiagnosis = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContainsDiagnosis");
                this.OnContainsDiagnosisChanged();
            }
        }
        private global::System.Nullable<bool> _ContainsDiagnosis;
        partial void OnContainsDiagnosisChanging(global::System.Nullable<bool> value);
        partial void OnContainsDiagnosisChanged();
        /// <summary>
        /// There are no comments for Property ContainsIntervention in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ContainsIntervention
        {
            get
            {
                return this._ContainsIntervention;
            }
            set
            {
                this.OnContainsInterventionChanging(value);
                this.ReportPropertyChanging("ContainsIntervention");
                this._ContainsIntervention = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContainsIntervention");
                this.OnContainsInterventionChanged();
            }
        }
        private global::System.Nullable<bool> _ContainsIntervention;
        partial void OnContainsInterventionChanging(global::System.Nullable<bool> value);
        partial void OnContainsInterventionChanged();
        /// <summary>
        /// There are no comments for Property ContainsCareComponent in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ContainsCareComponent
        {
            get
            {
                return this._ContainsCareComponent;
            }
            set
            {
                this.OnContainsCareComponentChanging(value);
                this.ReportPropertyChanging("ContainsCareComponent");
                this._ContainsCareComponent = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContainsCareComponent");
                this.OnContainsCareComponentChanged();
            }
        }
        private global::System.Nullable<bool> _ContainsCareComponent;
        partial void OnContainsCareComponentChanging(global::System.Nullable<bool> value);
        partial void OnContainsCareComponentChanged();
        /// <summary>
        /// There are no comments for Property ContainsFolksonomy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ContainsFolksonomy
        {
            get
            {
                return this._ContainsFolksonomy;
            }
            set
            {
                this.OnContainsFolksonomyChanging(value);
                this.ReportPropertyChanging("ContainsFolksonomy");
                this._ContainsFolksonomy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ContainsFolksonomy");
                this.OnContainsFolksonomyChanged();
            }
        }
        private global::System.Nullable<bool> _ContainsFolksonomy;
        partial void OnContainsFolksonomyChanging(global::System.Nullable<bool> value);
        partial void OnContainsFolksonomyChanged();
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Item_Annotation", "Annotation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<CPAnnotation> Annotation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CPAnnotation>("eNurseCP.BusinessLayer.FK_Item_Annotation", "Annotation");
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_CarePlan_Item", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlan CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("eNurseCP.BusinessLayer.FK_CarePlan_Item", "CarePlan").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("eNurseCP.BusinessLayer.FK_CarePlan_Item", "CarePlan").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlan> CarePlanReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("eNurseCP.BusinessLayer.FK_CarePlan_Item", "CarePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlan>("eNurseCP.BusinessLayer.FK_CarePlan_Item", "CarePlan", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_History_Item", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Item", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Item", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Item", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("eNurseCP.BusinessLayer.FK_History_Item", "History", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Tag_Item", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tag> Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tag>("eNurseCP.BusinessLayer.FK_Tag_Item", "Tag");
            }
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.Outcome in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="Outcome")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Outcome : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Outcome object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="expectedOutcome">Initial value of ExpectedOutcome.</param>
        /// <param name="taxonomyTagId">Initial value of TaxonomyTagId.</param>
        public static Outcome CreateOutcome(global::System.Guid ID, short expectedOutcome, global::System.Guid taxonomyTagId)
        {
            Outcome outcome = new Outcome();
            outcome.Id = ID;
            outcome.ExpectedOutcome = expectedOutcome;
            outcome.TaxonomyTagId = taxonomyTagId;
            return outcome;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ActualOutcome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> ActualOutcome
        {
            get
            {
                return this._ActualOutcome;
            }
            set
            {
                this.OnActualOutcomeChanging(value);
                this.ReportPropertyChanging("ActualOutcome");
                this._ActualOutcome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ActualOutcome");
                this.OnActualOutcomeChanged();
            }
        }
        private global::System.Nullable<short> _ActualOutcome;
        partial void OnActualOutcomeChanging(global::System.Nullable<short> value);
        partial void OnActualOutcomeChanged();
        /// <summary>
        /// There are no comments for Property ActualEvaluation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualEvaluation
        {
            get
            {
                return this._ActualEvaluation;
            }
            set
            {
                this.OnActualEvaluationChanging(value);
                this.ReportPropertyChanging("ActualEvaluation");
                this._ActualEvaluation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("ActualEvaluation");
                this.OnActualEvaluationChanged();
            }
        }
        private string _ActualEvaluation;
        partial void OnActualEvaluationChanging(string value);
        partial void OnActualEvaluationChanged();
        /// <summary>
        /// There are no comments for Property ActualDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ActualDate
        {
            get
            {
                return this._ActualDate;
            }
            set
            {
                this.OnActualDateChanging(value);
                this.ReportPropertyChanging("ActualDate");
                this._ActualDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("ActualDate");
                this.OnActualDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ActualDate;
        partial void OnActualDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnActualDateChanged();
        /// <summary>
        /// There are no comments for Property ExpectedOutcome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short ExpectedOutcome
        {
            get
            {
                return this._ExpectedOutcome;
            }
            set
            {
                this.OnExpectedOutcomeChanging(value);
                this.ReportPropertyChanging("ExpectedOutcome");
                this._ExpectedOutcome = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ExpectedOutcome");
                this.OnExpectedOutcomeChanged();
            }
        }
        private short _ExpectedOutcome;
        partial void OnExpectedOutcomeChanging(short value);
        partial void OnExpectedOutcomeChanged();
        /// <summary>
        /// There are no comments for Property ExpectedGoal in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpectedGoal
        {
            get
            {
                return this._ExpectedGoal;
            }
            set
            {
                this.OnExpectedGoalChanging(value);
                this.ReportPropertyChanging("ExpectedGoal");
                this._ExpectedGoal = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("ExpectedGoal");
                this.OnExpectedGoalChanged();
            }
        }
        private string _ExpectedGoal;
        partial void OnExpectedGoalChanging(string value);
        partial void OnExpectedGoalChanged();
        /// <summary>
        /// There are no comments for Property ExpectedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ExpectedDate
        {
            get
            {
                return this._ExpectedDate;
            }
            set
            {
                this.OnExpectedDateChanging(value);
                this.ReportPropertyChanging("ExpectedDate");
                this._ExpectedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("ExpectedDate");
                this.OnExpectedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ExpectedDate;
        partial void OnExpectedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnExpectedDateChanged();
        /// <summary>
        /// There are no comments for Property TaxonomyTagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonomyTagId
        {
            get
            {
                return this._TaxonomyTagId;
            }
            set
            {
                this.OnTaxonomyTagIdChanging(value);
                this.ReportPropertyChanging("TaxonomyTagId");
                this._TaxonomyTagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonomyTagId");
                this.OnTaxonomyTagIdChanged();
            }
        }
        private global::System.Guid _TaxonomyTagId;
        partial void OnTaxonomyTagIdChanging(global::System.Guid value);
        partial void OnTaxonomyTagIdChanged();
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Outcome_History", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_Outcome_History", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_Outcome_History", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_Outcome_History", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("eNurseCP.BusinessLayer.FK_Outcome_History", "History", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Outcome_Tag", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Tag Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Outcome_Tag", "Tag").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Outcome_Tag", "Tag").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Tag> TagReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Outcome_Tag", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tag>("eNurseCP.BusinessLayer.FK_Outcome_Tag", "Tag", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for eNurseCP.BusinessLayer.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="eNurseCP.BusinessLayer", Name="Tag")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Tag : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="taxonomyType">Initial value of TaxonomyType.</param>
        /// <param name="taxonomyTagId">Initial value of TaxonomyTagId.</param>
        public static Tag CreateTag(global::System.Guid ID, string taxonomyType, global::System.Guid taxonomyTagId)
        {
            Tag tag = new Tag();
            tag.Id = ID;
            tag.TaxonomyType = taxonomyType;
            tag.TaxonomyTagId = taxonomyTagId;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property TaxonomyType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxonomyType
        {
            get
            {
                return this._TaxonomyType;
            }
            set
            {
                this.OnTaxonomyTypeChanging(value);
                this.ReportPropertyChanging("TaxonomyType");
                this._TaxonomyType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 256);
                this.ReportPropertyChanged("TaxonomyType");
                this.OnTaxonomyTypeChanged();
            }
        }
        private string _TaxonomyType;
        partial void OnTaxonomyTypeChanging(string value);
        partial void OnTaxonomyTypeChanged();
        /// <summary>
        /// There are no comments for Property HistoryId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.Guid> HistoryId
        {
            get
            {
                return this._HistoryId;
            }
            set
            {
                this.OnHistoryIdChanging(value);
                this.ReportPropertyChanging("HistoryId");
                this._HistoryId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HistoryId");
                this.OnHistoryIdChanged();
            }
        }
        private global::System.Nullable<global::System.Guid> _HistoryId;
        partial void OnHistoryIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnHistoryIdChanged();
        /// <summary>
        /// There are no comments for Property TaxonomyTagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid TaxonomyTagId
        {
            get
            {
                return this._TaxonomyTagId;
            }
            set
            {
                this.OnTaxonomyTagIdChanging(value);
                this.ReportPropertyChanging("TaxonomyTagId");
                this._TaxonomyTagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonomyTagId");
                this.OnTaxonomyTagIdChanged();
            }
        }
        private global::System.Guid _TaxonomyTagId;
        partial void OnTaxonomyTagIdChanging(global::System.Guid value);
        partial void OnTaxonomyTagIdChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this.ReportPropertyChanging("Comment");
                this._Comment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 256);
                this.ReportPropertyChanged("Comment");
                this.OnCommentChanged();
            }
        }
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for ActionT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Tag_ActionT", "ActionT")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public ActionT ActionT
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ActionT>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "ActionT").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ActionT>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "ActionT").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for ActionT in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<ActionT> ActionTReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ActionT>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "ActionT");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ActionT>("eNurseCP.BusinessLayer.FK_Tag_ActionT", "ActionT", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Tag_History", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_Tag_History", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_Tag_History", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("eNurseCP.BusinessLayer.FK_Tag_History", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("eNurseCP.BusinessLayer.FK_Tag_History", "History", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Tag_Item", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Item Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Tag_Item", "Item").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Tag_Item", "Item").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Item> ItemReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Tag_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Item>("eNurseCP.BusinessLayer.FK_Tag_Item", "Item", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Outcome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("eNurseCP.BusinessLayer", "FK_Outcome_Tag", "Outcome")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Outcome> Outcome
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Outcome>("eNurseCP.BusinessLayer.FK_Outcome_Tag", "Outcome");
            }
        }
    }
}
