//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Annotation_CarePlan", "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.CarePlan), "Annotation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.CarePlanAnnotation))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Item_CarePlan", "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.CarePlan), "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.Item))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Tags_Item", "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.Item), "Tag", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.Tag))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Diagnosis_CarePlan", "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.CarePlan), "Diagnosis", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.CarePlanDiagnosis))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Outcome_Diagnosis", "Diagnosis", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.CarePlanDiagnosis), "Outcome", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.Outcome))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Item_History", "History", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CCC.BusinessLayer.History), "Item", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.Item))]

// Original file name:
// Generation date: 27.02.2008 14:18:09
namespace CCC.BusinessLayer
{
    
    /// <summary>
    /// There are no comments for CarePlanEntities in the schema.
    /// </summary>
    public partial class CarePlanEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CarePlanEntities object using the connection string found in the 'CarePlanEntities' section of the application configuration file.
        /// </summary>
        public CarePlanEntities() : 
                base("name=CarePlanEntities", "CarePlanEntities")
        {
        }
        /// <summary>
        /// Initialize a new CarePlanEntities object.
        /// </summary>
        public CarePlanEntities(string connectionString) : 
                base(connectionString, "CarePlanEntities")
        {
        }
        /// <summary>
        /// Initialize a new CarePlanEntities object.
        /// </summary>
        public CarePlanEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CarePlanEntities")
        {
        }
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<CarePlanAnnotation> Annotation
        {
            get
            {
                if ((this._Annotation == null))
                {
                    this._Annotation = base.CreateQuery<CarePlanAnnotation>("[Annotation]");
                }
                return this._Annotation;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarePlanAnnotation> _Annotation;
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<CarePlan> CarePlan
        {
            get
            {
                if ((this._CarePlan == null))
                {
                    this._CarePlan = base.CreateQuery<CarePlan>("[CarePlan]");
                }
                return this._CarePlan;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarePlan> _CarePlan;
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Item> Item
        {
            get
            {
                if ((this._Item == null))
                {
                    this._Item = base.CreateQuery<Item>("[Item]");
                }
                return this._Item;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Item> _Item;
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Tag> Tag
        {
            get
            {
                if ((this._Tag == null))
                {
                    this._Tag = base.CreateQuery<Tag>("[Tag]");
                }
                return this._Tag;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tag> _Tag;
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<CarePlanDiagnosis> Diagnosis
        {
            get
            {
                if ((this._Diagnosis == null))
                {
                    this._Diagnosis = base.CreateQuery<CarePlanDiagnosis>("[Diagnosis]");
                }
                return this._Diagnosis;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarePlanDiagnosis> _Diagnosis;
        /// <summary>
        /// There are no comments for OutcomeSet in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Outcome> OutcomeSet
        {
            get
            {
                if ((this._OutcomeSet == null))
                {
                    this._OutcomeSet = base.CreateQuery<Outcome>("[OutcomeSet]");
                }
                return this._OutcomeSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Outcome> _OutcomeSet;
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<History> History
        {
            get
            {
                if ((this._History == null))
                {
                    this._History = base.CreateQuery<History>("[History]");
                }
                return this._History;
            }
        }
        private global::System.Data.Objects.ObjectQuery<History> _History;
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        public void AddToAnnotation(CarePlanAnnotation carePlanAnnotation)
        {
            base.AddObject("Annotation", carePlanAnnotation);
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        public void AddToCarePlan(CarePlan carePlan)
        {
            base.AddObject("CarePlan", carePlan);
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        public void AddToItem(Item item)
        {
            base.AddObject("Item", item);
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        public void AddToTag(Tag tag)
        {
            base.AddObject("Tag", tag);
        }
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        public void AddToDiagnosis(CarePlanDiagnosis carePlanDiagnosis)
        {
            base.AddObject("Diagnosis", carePlanDiagnosis);
        }
        /// <summary>
        /// There are no comments for OutcomeSet in the schema.
        /// </summary>
        public void AddToOutcomeSet(Outcome outcome)
        {
            base.AddObject("OutcomeSet", outcome);
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        public void AddToHistory(History history)
        {
            base.AddObject("History", history);
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.CarePlanAnnotation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="CarePlanAnnotation")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class CarePlanAnnotation : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarePlanAnnotation object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static CarePlanAnnotation CreateCarePlanAnnotation(global::System.Guid ID)
        {
            CarePlanAnnotation carePlanAnnotation = new CarePlanAnnotation();
            carePlanAnnotation.Id = ID;
            return carePlanAnnotation;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private string _Data;
        partial void OnDataChanging(string value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Annotation_CarePlan", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlan CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlan> CarePlanReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.CarePlan in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="CarePlan")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class CarePlan : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarePlan object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static CarePlan CreateCarePlan(long ID)
        {
            CarePlan carePlan = new CarePlan();
            carePlan.Id = ID;
            return carePlan;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this.ReportPropertyChanging("PatientId");
                this._PatientId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PatientId");
                this.OnPatientIdChanged();
            }
        }
        private global::System.Nullable<int> _PatientId;
        partial void OnPatientIdChanging(global::System.Nullable<int> value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property TemplateCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> TemplateCategoryID
        {
            get
            {
                return this._TemplateCategoryID;
            }
            set
            {
                this.OnTemplateCategoryIDChanging(value);
                this.ReportPropertyChanging("TemplateCategoryID");
                this._TemplateCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TemplateCategoryID");
                this.OnTemplateCategoryIDChanged();
            }
        }
        private global::System.Nullable<short> _TemplateCategoryID;
        partial void OnTemplateCategoryIDChanging(global::System.Nullable<short> value);
        partial void OnTemplateCategoryIDChanged();
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Annotation_CarePlan", "Annotation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarePlanAnnotation> Annotation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarePlanAnnotation>("CCC.BusinessLayer.FK_Annotation_CarePlan", "Annotation");
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Item_CarePlan", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Item> Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Item>("CCC.BusinessLayer.FK_Item_CarePlan", "Item");
            }
        }
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Diagnosis_CarePlan", "Diagnosis")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<CarePlanDiagnosis> Diagnosis
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<CarePlanDiagnosis>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "Diagnosis");
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.Item in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="Item")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Item : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="description">Initial value of Description.</param>
        public static Item CreateItem(long ID, string title, byte[] description)
        {
            Item item = new Item();
            item.Id = ID;
            item.Title = title;
            item.Description = description;
            return item;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 255);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Description
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Description);
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 2147483647);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private byte[] _Description;
        partial void OnDescriptionChanging(byte[] value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Item_CarePlan", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlan CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Item_CarePlan", "CarePlan").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Item_CarePlan", "CarePlan").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlan> CarePlanReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Item_CarePlan", "CarePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Item_CarePlan", "CarePlan", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tag in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Tags_Item", "Tag")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Tag> Tag
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Tag>("CCC.BusinessLayer.FK_Tags_Item", "Tag");
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Item_History", "History")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public History History
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("CCC.BusinessLayer.FK_Item_History", "History").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("CCC.BusinessLayer.FK_Item_History", "History").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for History in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<History> HistoryReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<History>("CCC.BusinessLayer.FK_Item_History", "History");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<History>("CCC.BusinessLayer.FK_Item_History", "History", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="Tag")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Tag : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="taxonomyType">Initial value of TaxonomyType.</param>
        /// <param name="taxonomyTagId">Initial value of TaxonomyTagId.</param>
        public static Tag CreateTag(long ID, string taxonomyType, long taxonomyTagId)
        {
            Tag tag = new Tag();
            tag.Id = ID;
            tag.TaxonomyType = taxonomyType;
            tag.TaxonomyTagId = taxonomyTagId;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property TaxonomyType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxonomyType
        {
            get
            {
                return this._TaxonomyType;
            }
            set
            {
                this.OnTaxonomyTypeChanging(value);
                this.ReportPropertyChanging("TaxonomyType");
                this._TaxonomyType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 100);
                this.ReportPropertyChanged("TaxonomyType");
                this.OnTaxonomyTypeChanged();
            }
        }
        private string _TaxonomyType;
        partial void OnTaxonomyTypeChanging(string value);
        partial void OnTaxonomyTypeChanged();
        /// <summary>
        /// There are no comments for Property TaxonomyTagId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long TaxonomyTagId
        {
            get
            {
                return this._TaxonomyTagId;
            }
            set
            {
                this.OnTaxonomyTagIdChanging(value);
                this.ReportPropertyChanging("TaxonomyTagId");
                this._TaxonomyTagId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TaxonomyTagId");
                this.OnTaxonomyTagIdChanged();
            }
        }
        private long _TaxonomyTagId;
        partial void OnTaxonomyTagIdChanging(long value);
        partial void OnTaxonomyTagIdChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Tags_Item", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public Item Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("CCC.BusinessLayer.FK_Tags_Item", "Item").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("CCC.BusinessLayer.FK_Tags_Item", "Item").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<Item> ItemReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Item>("CCC.BusinessLayer.FK_Tags_Item", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Item>("CCC.BusinessLayer.FK_Tags_Item", "Item", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.CarePlanDiagnosis in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="CarePlanDiagnosis")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class CarePlanDiagnosis : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarePlanDiagnosis object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="version">Initial value of Version.</param>
        /// <param name="componentCode">Initial value of ComponentCode.</param>
        /// <param name="majorCode">Initial value of MajorCode.</param>
        public static CarePlanDiagnosis CreateCarePlanDiagnosis(int ID, string version, string componentCode, short majorCode)
        {
            CarePlanDiagnosis carePlanDiagnosis = new CarePlanDiagnosis();
            carePlanDiagnosis.Id = ID;
            carePlanDiagnosis.Version = version;
            carePlanDiagnosis.ComponentCode = componentCode;
            carePlanDiagnosis.MajorCode = majorCode;
            return carePlanDiagnosis;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this.ReportPropertyChanging("Version");
                this._Version = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 50);
                this.ReportPropertyChanged("Version");
                this.OnVersionChanged();
            }
        }
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property ComponentCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ComponentCode
        {
            get
            {
                return this._ComponentCode;
            }
            set
            {
                this.OnComponentCodeChanging(value);
                this.ReportPropertyChanging("ComponentCode");
                this._ComponentCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 1);
                this.ReportPropertyChanged("ComponentCode");
                this.OnComponentCodeChanged();
            }
        }
        private string _ComponentCode;
        partial void OnComponentCodeChanging(string value);
        partial void OnComponentCodeChanged();
        /// <summary>
        /// There are no comments for Property MajorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short MajorCode
        {
            get
            {
                return this._MajorCode;
            }
            set
            {
                this.OnMajorCodeChanging(value);
                this.ReportPropertyChanging("MajorCode");
                this._MajorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MajorCode");
                this.OnMajorCodeChanged();
            }
        }
        private short _MajorCode;
        partial void OnMajorCodeChanging(short value);
        partial void OnMajorCodeChanged();
        /// <summary>
        /// There are no comments for Property MinorCode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> MinorCode
        {
            get
            {
                return this._MinorCode;
            }
            set
            {
                this.OnMinorCodeChanging(value);
                this.ReportPropertyChanging("MinorCode");
                this._MinorCode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MinorCode");
                this.OnMinorCodeChanged();
            }
        }
        private global::System.Nullable<short> _MinorCode;
        partial void OnMinorCodeChanging(global::System.Nullable<short> value);
        partial void OnMinorCodeChanged();
        /// <summary>
        /// There are no comments for Property Focus in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Focus
        {
            get
            {
                return this._Focus;
            }
            set
            {
                this.OnFocusChanging(value);
                this.ReportPropertyChanging("Focus");
                this._Focus = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Focus");
                this.OnFocusChanged();
            }
        }
        private string _Focus;
        partial void OnFocusChanging(string value);
        partial void OnFocusChanged();
        /// <summary>
        /// There are no comments for Property Judgement in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Judgement
        {
            get
            {
                return this._Judgement;
            }
            set
            {
                this.OnJudgementChanging(value);
                this.ReportPropertyChanging("Judgement");
                this._Judgement = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 100);
                this.ReportPropertyChanged("Judgement");
                this.OnJudgementChanged();
            }
        }
        private string _Judgement;
        partial void OnJudgementChanging(string value);
        partial void OnJudgementChanged();
        /// <summary>
        /// There are no comments for Property ReasonForDiagnosis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonForDiagnosis
        {
            get
            {
                return this._ReasonForDiagnosis;
            }
            set
            {
                this.OnReasonForDiagnosisChanging(value);
                this.ReportPropertyChanging("ReasonForDiagnosis");
                this._ReasonForDiagnosis = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 500);
                this.ReportPropertyChanged("ReasonForDiagnosis");
                this.OnReasonForDiagnosisChanged();
            }
        }
        private string _ReasonForDiagnosis;
        partial void OnReasonForDiagnosisChanging(string value);
        partial void OnReasonForDiagnosisChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this.ReportPropertyChanging("CreationDate");
                this._CreationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("CreationDate");
                this.OnCreationDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property CreatorEmployeeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CreatorEmployeeId
        {
            get
            {
                return this._CreatorEmployeeId;
            }
            set
            {
                this.OnCreatorEmployeeIdChanging(value);
                this.ReportPropertyChanging("CreatorEmployeeId");
                this._CreatorEmployeeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatorEmployeeId");
                this.OnCreatorEmployeeIdChanged();
            }
        }
        private global::System.Nullable<int> _CreatorEmployeeId;
        partial void OnCreatorEmployeeIdChanging(global::System.Nullable<int> value);
        partial void OnCreatorEmployeeIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return this._LastUpdateDate;
            }
            set
            {
                this.OnLastUpdateDateChanging(value);
                this.ReportPropertyChanging("LastUpdateDate");
                this._LastUpdateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("LastUpdateDate");
                this.OnLastUpdateDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();
        /// <summary>
        /// There are no comments for Property UpdateEmployeeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> UpdateEmployeeId
        {
            get
            {
                return this._UpdateEmployeeId;
            }
            set
            {
                this.OnUpdateEmployeeIdChanging(value);
                this.ReportPropertyChanging("UpdateEmployeeId");
                this._UpdateEmployeeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpdateEmployeeId");
                this.OnUpdateEmployeeIdChanged();
            }
        }
        private global::System.Nullable<int> _UpdateEmployeeId;
        partial void OnUpdateEmployeeIdChanging(global::System.Nullable<int> value);
        partial void OnUpdateEmployeeIdChanged();
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Diagnosis_CarePlan", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlan CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlan> CarePlanReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Outcome in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Outcome_Diagnosis", "Outcome")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Outcome> Outcome
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Outcome>("CCC.BusinessLayer.FK_Outcome_Diagnosis", "Outcome");
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.Outcome in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Expected
    /// EvalDate
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="Outcome")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Outcome : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Outcome object.
        /// </summary>
        /// <param name="expected">Initial value of Expected.</param>
        /// <param name="evalDate">Initial value of EvalDate.</param>
        public static Outcome CreateOutcome(short expected, global::System.DateTime evalDate)
        {
            Outcome outcome = new Outcome();
            outcome.Expected = expected;
            outcome.EvalDate = evalDate;
            return outcome;
        }
        /// <summary>
        /// There are no comments for Property Expected in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public short Expected
        {
            get
            {
                return this._Expected;
            }
            set
            {
                this.OnExpectedChanging(value);
                this.ReportPropertyChanging("Expected");
                this._Expected = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Expected");
                this.OnExpectedChanged();
            }
        }
        private short _Expected;
        partial void OnExpectedChanging(short value);
        partial void OnExpectedChanged();
        /// <summary>
        /// There are no comments for Property EvalDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime EvalDate
        {
            get
            {
                return this._EvalDate;
            }
            set
            {
                this.OnEvalDateChanging(value);
                this.ReportPropertyChanging("EvalDate");
                this._EvalDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("EvalDate");
                this.OnEvalDateChanged();
            }
        }
        private global::System.DateTime _EvalDate;
        partial void OnEvalDateChanging(global::System.DateTime value);
        partial void OnEvalDateChanged();
        /// <summary>
        /// There are no comments for Property EvalComment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EvalComment
        {
            get
            {
                return this._EvalComment;
            }
            set
            {
                this.OnEvalCommentChanging(value);
                this.ReportPropertyChanging("EvalComment");
                this._EvalComment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("EvalComment");
                this.OnEvalCommentChanged();
            }
        }
        private string _EvalComment;
        partial void OnEvalCommentChanging(string value);
        partial void OnEvalCommentChanged();
        /// <summary>
        /// There are no comments for Property Actual in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> Actual
        {
            get
            {
                return this._Actual;
            }
            set
            {
                this.OnActualChanging(value);
                this.ReportPropertyChanging("Actual");
                this._Actual = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Actual");
                this.OnActualChanged();
            }
        }
        private global::System.Nullable<short> _Actual;
        partial void OnActualChanging(global::System.Nullable<short> value);
        partial void OnActualChanged();
        /// <summary>
        /// There are no comments for Property ActualEvalDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> ActualEvalDate
        {
            get
            {
                return this._ActualEvalDate;
            }
            set
            {
                this.OnActualEvalDateChanging(value);
                this.ReportPropertyChanging("ActualEvalDate");
                this._ActualEvalDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("ActualEvalDate");
                this.OnActualEvalDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _ActualEvalDate;
        partial void OnActualEvalDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnActualEvalDateChanged();
        /// <summary>
        /// There are no comments for Property ActualComment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualComment
        {
            get
            {
                return this._ActualComment;
            }
            set
            {
                this.OnActualCommentChanging(value);
                this.ReportPropertyChanging("ActualComment");
                this._ActualComment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("ActualComment");
                this.OnActualCommentChanged();
            }
        }
        private string _ActualComment;
        partial void OnActualCommentChanging(string value);
        partial void OnActualCommentChanged();
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Outcome_Diagnosis", "Diagnosis")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlanDiagnosis Diagnosis
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlanDiagnosis>("CCC.BusinessLayer.FK_Outcome_Diagnosis", "Diagnosis").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlanDiagnosis>("CCC.BusinessLayer.FK_Outcome_Diagnosis", "Diagnosis").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlanDiagnosis> DiagnosisReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlanDiagnosis>("CCC.BusinessLayer.FK_Outcome_Diagnosis", "Diagnosis");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlanDiagnosis>("CCC.BusinessLayer.FK_Outcome_Diagnosis", "Diagnosis", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.History in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="History")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class History : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new History object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        public static History CreateHistory(long ID, global::System.DateTime createdDate, string createdBy)
        {
            History history = new History();
            history.Id = ID;
            history.CreatedDate = createdDate;
            history.CreatedBy = createdBy;
            return history;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false, 150);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property UpdatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
            set
            {
                this.OnUpdatedDateChanging(value);
                this.ReportPropertyChanging("UpdatedDate");
                this._UpdatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("UpdatedDate");
                this.OnUpdatedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnUpdatedDateChanged();
        /// <summary>
        /// There are no comments for Property UpdatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdatedBy
        {
            get
            {
                return this._UpdatedBy;
            }
            set
            {
                this.OnUpdatedByChanging(value);
                this.ReportPropertyChanging("UpdatedBy");
                this._UpdatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 150);
                this.ReportPropertyChanged("UpdatedBy");
                this.OnUpdatedByChanged();
            }
        }
        private string _UpdatedBy;
        partial void OnUpdatedByChanging(string value);
        partial void OnUpdatedByChanged();
        /// <summary>
        /// There are no comments for Item in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Item_History", "Item")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Item> Item
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Item>("CCC.BusinessLayer.FK_Item_History", "Item");
            }
        }
    }
}
