<?xml version="1.0" encoding="utf-8"?>
<Database Name="Pleieplan" Class="CarePlanTemplateDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=&quot;C:\Programfiler\Microsoft SQL Server\MSSQL.1\MSSQL\Data\Pleieplan.mdf&quot;;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="CCC.BusinessLayer.Properties.Settings" SettingsPropertyName="PleieplanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TemplateCarePlan" Member="TemplateCarePlans">
    <Type Name="TemplateCarePlan">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>