//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Annotation_CarePlan", "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.CarePlan), "Annotation", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.Annot))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("CCC.BusinessLayer", "FK_Diagnosis_CarePlan", "CarePlan", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CCC.BusinessLayer.CarePlan), "Diagnosis", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CCC.BusinessLayer.Diagnosi))]

// Original file name:
// Generation date: 09.01.2008 20:36:32
namespace CCC.BusinessLayer
{
    
    /// <summary>
    /// There are no comments for PleieplanEntitiesv2 in the schema.
    /// </summary>
    public partial class PleieplanEntitiesv2 : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new PleieplanEntitiesv2 object using the connection string found in the 'PleieplanEntitiesv2' section of the application configuration file.
        /// </summary>
        public PleieplanEntitiesv2() : 
                base("name=PleieplanEntitiesv2", "PleieplanEntitiesv2")
        {
        }
        /// <summary>
        /// Initialize a new PleieplanEntitiesv2 object.
        /// </summary>
        public PleieplanEntitiesv2(string connectionString) : 
                base(connectionString, "PleieplanEntitiesv2")
        {
        }
        /// <summary>
        /// Initialize a new PleieplanEntitiesv2 object.
        /// </summary>
        public PleieplanEntitiesv2(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "PleieplanEntitiesv2")
        {
        }
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Annot> Annotation
        {
            get
            {
                if ((this._Annotation == null))
                {
                    this._Annotation = base.CreateQuery<Annot>("[Annotation]");
                }
                return this._Annotation;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Annot> _Annotation;
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<CarePlan> CarePlan
        {
            get
            {
                if ((this._CarePlan == null))
                {
                    this._CarePlan = base.CreateQuery<CarePlan>("[CarePlan]");
                }
                return this._CarePlan;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CarePlan> _CarePlan;
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<Diagnosi> Diagnosis
        {
            get
            {
                if ((this._Diagnosis == null))
                {
                    this._Diagnosis = base.CreateQuery<Diagnosi>("[Diagnosis]");
                }
                return this._Diagnosis;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Diagnosi> _Diagnosis;
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        public void AddToAnnotation(Annot annot)
        {
            base.AddObject("Annotation", annot);
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        public void AddToCarePlan(CarePlan carePlan)
        {
            base.AddObject("CarePlan", carePlan);
        }
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        public void AddToDiagnosis(Diagnosi diagnosi)
        {
            base.AddObject("Diagnosis", diagnosi);
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.Annot in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="Annot")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Annot : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Annot object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static Annot CreateAnnot(global::System.Guid ID)
        {
            Annot annot = new Annot();
            annot.Id = ID;
            return annot;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Data
        {
            get
            {
                return this._Data;
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 2147483647);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private string _Data;
        partial void OnDataChanging(string value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Annotation_CarePlan", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlan CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlan> CarePlanReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Annotation_CarePlan", "CarePlan", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for CCC.BusinessLayer.CarePlan in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="CarePlan")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class CarePlan : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CarePlan object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static CarePlan CreateCarePlan(int ID)
        {
            CarePlan carePlan = new CarePlan();
            carePlan.Id = ID;
            return carePlan;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 50);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property PatientId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                this.OnPatientIdChanging(value);
                this.ReportPropertyChanging("PatientId");
                this._PatientId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PatientId");
                this.OnPatientIdChanged();
            }
        }
        private global::System.Nullable<int> _PatientId;
        partial void OnPatientIdChanging(global::System.Nullable<int> value);
        partial void OnPatientIdChanged();
        /// <summary>
        /// There are no comments for Property TemplateCategoryID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<short> TemplateCategoryID
        {
            get
            {
                return this._TemplateCategoryID;
            }
            set
            {
                this.OnTemplateCategoryIDChanging(value);
                this.ReportPropertyChanging("TemplateCategoryID");
                this._TemplateCategoryID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TemplateCategoryID");
                this.OnTemplateCategoryIDChanged();
            }
        }
        private global::System.Nullable<short> _TemplateCategoryID;
        partial void OnTemplateCategoryIDChanging(global::System.Nullable<short> value);
        partial void OnTemplateCategoryIDChanged();
        /// <summary>
        /// There are no comments for Annotation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Annotation_CarePlan", "Annotation")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Annot> Annotation
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Annot>("CCC.BusinessLayer.FK_Annotation_CarePlan", "Annotation");
            }
        }
        /// <summary>
        /// There are no comments for Diagnosis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Diagnosis_CarePlan", "Diagnosis")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityCollection<Diagnosi> Diagnosis
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Diagnosi>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "Diagnosis");
            }
        }
    }
    /// <summary>
    /// Diagnoses
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CCC.BusinessLayer", Name="Diagnosi")]
    [global::System.Runtime.Serialization.DataContractAttribute()]
    [global::System.Serializable()]
    public partial class Diagnosi : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Diagnosi object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static Diagnosi CreateDiagnosi(int ID)
        {
            Diagnosi diagnosi = new Diagnosi();
            diagnosi.Id = ID;
            return diagnosi;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property cccId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> cccId
        {
            get
            {
                return this._cccId;
            }
            set
            {
                this.OncccIdChanging(value);
                this.ReportPropertyChanging("cccId");
                this._cccId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cccId");
                this.OncccIdChanged();
            }
        }
        private global::System.Nullable<int> _cccId;
        partial void OncccIdChanging(global::System.Nullable<int> value);
        partial void OncccIdChanged();
        /// <summary>
        /// There are no comments for Property Focus in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Focus
        {
            get
            {
                return this._Focus;
            }
            set
            {
                this.OnFocusChanging(value);
                this.ReportPropertyChanging("Focus");
                this._Focus = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 255);
                this.ReportPropertyChanged("Focus");
                this.OnFocusChanged();
            }
        }
        private string _Focus;
        partial void OnFocusChanging(string value);
        partial void OnFocusChanged();
        /// <summary>
        /// There are no comments for Property Judgement in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Judgement
        {
            get
            {
                return this._Judgement;
            }
            set
            {
                this.OnJudgementChanging(value);
                this.ReportPropertyChanging("Judgement");
                this._Judgement = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 100);
                this.ReportPropertyChanged("Judgement");
                this.OnJudgementChanged();
            }
        }
        private string _Judgement;
        partial void OnJudgementChanging(string value);
        partial void OnJudgementChanged();
        /// <summary>
        /// There are no comments for Property ReasonForDiagnosis in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonForDiagnosis
        {
            get
            {
                return this._ReasonForDiagnosis;
            }
            set
            {
                this.OnReasonForDiagnosisChanging(value);
                this.ReportPropertyChanging("ReasonForDiagnosis");
                this._ReasonForDiagnosis = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true, 500);
                this.ReportPropertyChanged("ReasonForDiagnosis");
                this.OnReasonForDiagnosisChanged();
            }
        }
        private string _ReasonForDiagnosis;
        partial void OnReasonForDiagnosisChanging(string value);
        partial void OnReasonForDiagnosisChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this.ReportPropertyChanging("CreationDate");
                this._CreationDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("CreationDate");
                this.OnCreationDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property CreatorEmployeeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> CreatorEmployeeId
        {
            get
            {
                return this._CreatorEmployeeId;
            }
            set
            {
                this.OnCreatorEmployeeIdChanging(value);
                this.ReportPropertyChanging("CreatorEmployeeId");
                this._CreatorEmployeeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatorEmployeeId");
                this.OnCreatorEmployeeIdChanged();
            }
        }
        private global::System.Nullable<int> _CreatorEmployeeId;
        partial void OnCreatorEmployeeIdChanging(global::System.Nullable<int> value);
        partial void OnCreatorEmployeeIdChanged();
        /// <summary>
        /// There are no comments for Property LastUpdateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> LastUpdateDate
        {
            get
            {
                return this._LastUpdateDate;
            }
            set
            {
                this.OnLastUpdateDateChanging(value);
                this.ReportPropertyChanging("LastUpdateDate");
                this._LastUpdateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, global::System.DateTimeKind.Unspecified, true);
                this.ReportPropertyChanged("LastUpdateDate");
                this.OnLastUpdateDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _LastUpdateDate;
        partial void OnLastUpdateDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastUpdateDateChanged();
        /// <summary>
        /// There are no comments for Property UpdateEmployeeId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> UpdateEmployeeId
        {
            get
            {
                return this._UpdateEmployeeId;
            }
            set
            {
                this.OnUpdateEmployeeIdChanging(value);
                this.ReportPropertyChanging("UpdateEmployeeId");
                this._UpdateEmployeeId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UpdateEmployeeId");
                this.OnUpdateEmployeeIdChanged();
            }
        }
        private global::System.Nullable<int> _UpdateEmployeeId;
        partial void OnUpdateEmployeeIdChanging(global::System.Nullable<int> value);
        partial void OnUpdateEmployeeIdChanged();
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("CCC.BusinessLayer", "FK_Diagnosis_CarePlan", "CarePlan")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public CarePlan CarePlan
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for CarePlan in the schema.
        /// </summary>
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.DataClasses.EntityReference<CarePlan> CarePlanReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<CarePlan>("CCC.BusinessLayer.FK_Diagnosis_CarePlan", "CarePlan", value);
                }
            }
        }
    }
}
